name: image_pieces
description: Very large image support.
version: 0.1.0
homepage: https://github.com/yrom/image_pieces
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image: ^2.1.19
  path_provider: ^1.6.18
  raw_image_provider: ^0.1.0
  executor: 
    git: https://github.com/yrom/dart-executor.git
dev_dependencies:
  flutter_test:
    sdk: flutter
